In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
from tqdm.notebook import tqdm
import scipy
import sklearn
cwd = Path('.')

In [20]:
data_path = cwd / 'data' / '2025_LoL_esports_match_data_from_OraclesElixir_imputated.csv'
data = pd.read_csv(data_path,index_col=0)
data_len = int(len(data) * 10 / 12)

C:\Users\victo\AppData\Local\Temp\ipykernel_12224\4154608675.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(data_path,index_col=0)

In [21]:
data = data.drop(data[data["position"] == "team"].index)

In [23]:
pick_set = []
ban_set = []
for i in tqdm(range(0,len(data),5)):
    data_game = data.iloc[i:i+5]
    pick_set_game = []
    ban_set_game = []
    champs_in_game = data_game["champion"]
    if (data_game["ban1"].hasnans == False): #Some bans are missing for some games, these are assumed to be as a result of a team using all their time and missing the opputunity to ban and as such the game can sstill be kept
        ban_set_game.append(data_game.iloc[0]["ban1"]+"_banned")
    if (data_game["ban2"].hasnans == False):
        ban_set_game.append(data_game.iloc[0]["ban2"]+"_banned")
    if (data_game["ban3"].hasnans == False):
        ban_set_game.append(data_game.iloc[0]["ban3"]+"_banned")
    if (data_game["ban4"].hasnans == False):
        ban_set_game.append(data_game.iloc[0]["ban4"]+"_banned")
    if (data_game["ban5"].hasnans == False):
        ban_set_game.append(data_game.iloc[0]["ban5"]+"_banned")
    for champ in champs_in_game:
        champ_name = champ + "_picked"
        pick_set_game.append(champ_name)
    pick_set.append(pick_set_game)
    ban_set.append(np.unique(ban_set_game))

  0%|          | 0/20106 [00:00<?, ?it/s]

In [24]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(pick_set).transform(pick_set)
df_ap = pd.DataFrame(te_ary, columns=te.columns_)

In [25]:
df_ap

,Aatrox_picked,Ahri_picked,Akali_picked,Akshan_picked,Alistar_picked,Ambessa_picked,Amumu_picked,Anivia_picked,Annie_picked,Aphelios_picked,...,Yunara_picked,Yuumi_picked,Zaahen_picked,Zac_picked,Zed_picked,Zeri_picked,Ziggs_picked,Zilean_picked,Zoe_picked,Zyra_picked
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,True,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20101,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20102,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
20103,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20104,True,True,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
20105,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [26]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(df_ap, min_support=0.01,use_colnames=True)

We need to use a very low support to get sets of a size greater than 1 since there are only ever 5 champions and very many combinations of them.

In [27]:
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

In [28]:
freq_greater_1 = frequent_itemsets[(frequent_itemsets['length'])>1]

In [29]:
freq_greater_1.sort_values(by=["support"])

      support                           itemsets  length
88   0.010047      (Ambessa_picked, Ahri_picked)       2
170  0.010047  (K'Sante_picked, Nautilus_picked)       2
196  0.010096     (Rakan_picked, Orianna_picked)       2
188  0.010146       (Maokai_picked, Rell_picked)       2
195  0.010146  (Nocturne_picked, Orianna_picked)       2
..        ...                                ...     ...
208  0.020790       (Rumble_picked, Rell_picked)       2
153  0.022481      (Leona_picked, Ezreal_picked)       2
212  0.022879        (Varus_picked, Rell_picked)       2
145  0.024072        (Rell_picked, Corki_picked)       2
206  0.027852       (Xayah_picked, Rakan_picked)       2

[148 rows x 3 columns]

Xayah and Rakan are a typical combo so seeing them with the highest support is good

In [30]:
from mlxtend.frequent_patterns import fpgrowth

In [31]:
frequent_itemsets_fpg = fpgrowth(df_ap, min_support=0.01,use_colnames=True)

In [32]:
frequent_itemsets_fpg['length'] = frequent_itemsets_fpg['itemsets'].apply(lambda x: len(x))
freq_greater_1_fpg = frequent_itemsets_fpg[(frequent_itemsets_fpg['length'])>1]
freq_greater_1_fpg.sort_values(by=["support"])

      support                           itemsets  length
123  0.010047  (K'Sante_picked, Nautilus_picked)       2
184  0.010047      (Ambessa_picked, Ahri_picked)       2
100  0.010096     (Rakan_picked, Orianna_picked)       2
93   0.010146       (Maokai_picked, Rell_picked)       2
166  0.010146      (Varus_picked, Viktor_picked)       2
..        ...                                ...     ...
192  0.020790       (Rumble_picked, Rell_picked)       2
89   0.022481      (Leona_picked, Ezreal_picked)       2
96   0.022879        (Varus_picked, Rell_picked)       2
126  0.024072        (Rell_picked, Corki_picked)       2
227  0.027852       (Xayah_picked, Rakan_picked)       2

[148 rows x 3 columns]

In [33]:
pick_ban_set = [] # First is champ selected, second is ban
for i in range(len(pick_set)):
    for champ in pick_set[i]:
        for ban in ban_set[i]:
            pick_ban_set.append([champ,ban])

In [34]:
te = TransactionEncoder()
te_ary = te.fit(pick_ban_set).transform(pick_ban_set)
df_ap_pb = pd.DataFrame(te_ary, columns=te.columns_)

In [88]:
frequent_itemsets_pb = fpgrowth(df_ap_pb, min_support=0.0005,use_colnames=True)
frequent_itemsets_pb['length'] = frequent_itemsets_pb['itemsets'].apply(lambda x: len(x))
freq_greater_1_pb = frequent_itemsets_pb[(frequent_itemsets_pb['length'])>1]
freq_greater_1_pb.sort_values(by=["support"])

      support                          itemsets  length
309  0.000503  (Sejuani_picked, Skarner_banned)       2
362  0.000503     (Varus_banned, Viktor_picked)       2
253  0.000503      (Jayce_banned, Leona_picked)       2
467  0.000505   (Neeko_banned, Nautilus_picked)       2
354  0.000505  (Ambessa_banned, Alistar_picked)       2
..        ...                               ...     ...
492  0.001121        (Sion_picked, Gwen_banned)       2
303  0.001131          (Vi_banned, Rell_picked)       2
443  0.001139   (Varus_banned, Xin Zhao_picked)       2
439  0.001153      (Vi_banned, Xin Zhao_picked)       2
305  0.001175       (Varus_banned, Rell_picked)       2

[258 rows x 3 columns]

In [36]:
frequent_itemsets_pb.iloc[0]["itemsets"]==set(["Corki_banned"])

True

In [25]:
print(frequent_itemsets_pb[frequent_itemsets_pb["itemsets"]==set(["Varus_banned"])]["support"])
frequent_itemsets_pb[frequent_itemsets_pb["itemsets"]==set(["Rell_picked"])]["support"]

86    0.03797
Name: support, dtype: float64

25    0.030006
Name: support, dtype: float64

In [89]:
common_pick_ban = freq_greater_1_pb.sort_values(by=["support"])

In [90]:
common_pick_ban

      support                          itemsets  length
309  0.000503  (Sejuani_picked, Skarner_banned)       2
362  0.000503     (Varus_banned, Viktor_picked)       2
253  0.000503      (Jayce_banned, Leona_picked)       2
467  0.000505   (Neeko_banned, Nautilus_picked)       2
354  0.000505  (Ambessa_banned, Alistar_picked)       2
..        ...                               ...     ...
492  0.001121        (Sion_picked, Gwen_banned)       2
303  0.001131          (Vi_banned, Rell_picked)       2
443  0.001139   (Varus_banned, Xin Zhao_picked)       2
439  0.001153      (Vi_banned, Xin Zhao_picked)       2
305  0.001175       (Varus_banned, Rell_picked)       2

[258 rows x 3 columns]

In [51]:
common_pick_ban.iloc[pick_ban_index]

support                           0.001005
itemsets    (Alistar_picked, Varus_banned)
length                                   2
Name: 206, dtype: object

In [69]:
for i in common_pick_ban.iloc[pick_ban_index]["itemsets"]:
    print(i)

Varus_banned
Rell_picked

In [71]:
common_pick_ban.iloc[pick_ban_index]["itemsets"]

frozenset({'Rell_picked', np.str_('Varus_banned')})

In [91]:
norms = []
for pick_ban_index in range(len(common_pick_ban)):
    k = 1
    for i in common_pick_ban.iloc[pick_ban_index]["itemsets"]:
        k = k * frequent_itemsets_pb[frequent_itemsets_pb["itemsets"]==set([i])]["support"].iloc[0]
    norm_support = common_pick_ban.iloc[pick_ban_index]["support"] / k
    norms.append(norm_support)
common_pick_ban["norm_support"] = norms

In [96]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(common_pick_ban.sort_values(by=["norm_support"])[20:])

      support                               itemsets  length  norm_support
333  0.000589       (Alistar_picked, Kalista_banned)       2      0.919517
362  0.000503          (Varus_banned, Viktor_picked)       2      0.924869
268  0.000551         (Varus_banned, Orianna_picked)       2      0.925509
477  0.000505       (Kai'Sa_picked, Pantheon_banned)       2      0.926746
337  0.000691          (Azir_banned, Alistar_picked)       2      0.927040
487  0.000579               (Vi_banned, Sion_picked)       2      0.927299
287  0.000621          (K'Sante_picked, Gwen_banned)       2      0.929370
304  0.000873           (Rumble_banned, Rell_picked)       2      0.930883
257  0.000521           (Aurora_banned, Rell_picked)       2      0.940855
282  0.000545            (Braum_picked, Gwen_banned)       2      0.942419
255  0.000677            (Leona_picked, Gwen_banned)       2      0.945977
425  0.000577            (Jhin_picked, Varus_banned)       2      0.949635
454  0.000537           (Vi_picked, Pantheon_banned)       2      0.954496
265  0.000599             (Yone_banned, Rell_picked)       2      0.955826
295  0.000537            (Poppy_banned, Azir_picked)       2      0.958910
354  0.000505       (Ambessa_banned, Alistar_picked)       2      0.960179
332  0.000529           (Gwen_banned, Aurora_picked)       2      0.961755
290  0.000561          (Azir_banned, K'Sante_picked)       2      0.962224
451  0.000581             (Vi_picked, Rumble_banned)       2      0.962269
496  0.000841         (Pantheon_banned, Rell_picked)       2      0.962307
271  0.000539          (Gwen_banned, Orianna_picked)       2      0.965054
322  0.000673       (Nautilus_picked, Rumble_banned)       2      0.966529
327  0.000671         (Azir_banned, Nautilus_picked)       2      0.968925
386  0.000601            (Varus_banned, Ahri_picked)       2      0.970539
417  0.000841            (Vi_banned, Ambessa_picked)       2      0.975436
252  0.000613          (Leona_picked, Rumble_banned)       2      0.976326
307  0.000911             (Azir_banned, Rell_picked)       2      0.976662
291  0.000659            (K'Sante_picked, Vi_banned)       2      0.977921
371  0.000801           (Ezreal_picked, Gwen_banned)       2      0.985038
476  0.000577         (Kai'Sa_picked, Rumble_banned)       2      0.986552
389  0.000691          (Rakan_picked, Rumble_banned)       2      0.987649
316  0.000845              (Vi_banned, Corki_picked)       2      0.988295
324  0.000837        (Nautilus_picked, Varus_banned)       2      0.989251
478  0.000661           (Kai'Sa_picked, Gwen_banned)       2      0.991458
398  0.000555           (Jayce_banned, Corki_picked)       2      0.992634
385  0.000583               (Vi_banned, Ahri_picked)       2      0.995194
242  0.000557      (Xin Zhao_picked, Skarner_banned)       2      0.996993
401  0.000563         (Jayce_banned, Ambessa_picked)       2      0.998536
402  0.000563         (Jayce_banned, Alistar_picked)       2      0.999284
288  0.000713         (K'Sante_picked, Varus_banned)       2      1.000875
391  0.000529           (Jayce_banned, Rakan_picked)       2      1.005903
293  0.000721      (Kalista_banned, Xin Zhao_picked)       2      1.006454
491  0.000665            (Sion_picked, Varus_banned)       2      1.007367
473  0.000587           (Azir_banned, Kai'Sa_picked)       2      1.009103
326  0.000655     (Nautilus_picked, Pantheon_banned)       2      1.009432
450  0.000741              (Vi_picked, Varus_banned)       2      1.009916
373  0.000615         (Wukong_picked, Rumble_banned)       2      1.012831
280  0.000625           (Braum_picked, Varus_banned)       2      1.013699
330  0.000595          (Varus_banned, Aurora_picked)       2      1.014654
281  0.000593              (Braum_picked, Vi_banned)       2      1.016716
455  0.000705               (Vi_picked, Gwen_banned)       2      1.024242
413  0.000823           (Rumble_picked, Gwen_banned)       2      1.025429
396  0.000669        (Rakan_picked, Pantheon_banned)       2      1.026099
306  0.001099             (Gwen_banned, Rell_picked)       2      1.028017
464  0.000515         (Neeko_banned, Ambessa_picked)       2      1.029498
321  0.000825           (Vi_banned, Nautilus_picked)       2      1.030673
305  0.001175            (Varus_banned, Rell_picked)       2      1.031095
397  0.000823            (Rakan_picked, Gwen_banned)       2      1.031924
355  0.000607      (Ambessa_banned, Xin Zhao_picked)       2      1.031939
494  0.000523            (Varus_banned, Ryze_picked)       2      1.033123
356  0.000553         (Ambessa_banned, Varus_picked)       2      1.035140
458  0.000575       (Alistar_picked, Taliyah_banned)       2      1.035955
278  0.000899            (Varus_picked, Gwen_banned)       2      1.036050
412  0.000681       (Rumble_picked, Pantheon_banned)       2      1.037902
318  0.000769            (Azir_banned, Corki_picked)       2      1.039411
453  0.000625               (Azir_banned, Vi_picked)       2      1.040672
422  0.000729      (Pantheon_banned, Ambessa_picked)       2      1.042898
367  0.000747         (Rumble_banned, Ezreal_picked)       2      1.047022
283  0.000525       (K'Sante_picked, Kalista_banned)       2      1.047711
303  0.001131               (Vi_banned, Rell_picked)       2      1.049097
419  0.000789        (Rumble_banned, Ambessa_picked)       2      1.051787
461  0.000731          (Taliyah_banned, Rell_picked)       2      1.052414
352  0.000693          (Ambessa_banned, Rell_picked)       2      1.052734
376  0.000777          (Wukong_picked, Varus_banned)       2      1.053037
348  0.000537         (Taliyah_picked, Jayce_banned)       2      1.053515
319  0.000731        (Pantheon_banned, Corki_picked)       2      1.054532
460  0.000581         (Taliyah_banned, Corki_picked)       2      1.054740
462  0.000661            (Neeko_banned, Rell_picked)       2      1.056615
315  0.000733           (Poppy_banned, Corki_picked)       2      1.059229
435  0.000509           (Poppy_picked, Varus_banned)       2      1.059620
433  0.000545     (Gwen_banned, Miss Fortune_picked)       2      1.060727
285  0.000579         (Poppy_banned, K'Sante_picked)       2      1.061611
328  0.000843         (Nautilus_picked, Gwen_banned)       2      1.061993
320  0.000633      (Kalista_banned, Nautilus_picked)       2      1.063472
410  0.000745           (Azir_banned, Rumble_picked)       2      1.063797
266  0.000533          (Yone_banned, Alistar_picked)       2      1.064171
400  0.000751            (Jayce_banned, Rell_picked)       2      1.065087
253  0.000503           (Jayce_banned, Leona_picked)       2      1.065714
360  0.000595           (Jayce_picked, Varus_banned)       2      1.066642
403  0.000673        (Jayce_banned, Xin Zhao_picked)       2      1.068116
407  0.000865             (Rumble_picked, Vi_banned)       2      1.068705
292  0.000857          (Kalista_banned, Rell_picked)       2      1.068938
418  0.000975         (Varus_banned, Ambessa_picked)       2      1.069691
312  0.000681         (Kalista_banned, Corki_picked)       2      1.071018
395  0.000555         (Rakan_picked, Taliyah_banned)       2      1.071182
325  0.000561        (Jayce_banned, Nautilus_picked)       2      1.071704
381  0.000547           (Rumble_banned, Ahri_picked)       2      1.073222
456  0.000597       (Taliyah_banned, Ambessa_picked)       2      1.074717
263  0.000513           (Yone_banned, Ezreal_picked)       2      1.076122
340  0.000921          (Alistar_picked, Gwen_banned)       2      1.077907
346  0.000681         (Taliyah_picked, Poppy_banned)       2      1.079500
336  0.000931            (Alistar_picked, Vi_banned)       2      1.080508
421  0.000695       (Kalista_banned, Ambessa_picked)       2      1.083906
467  0.000505        (Neeko_banned, Nautilus_picked)       2      1.087378
262  0.000611         (Yone_banned, Xin Zhao_picked)       2      1.090863
302  0.000749             (Azir_picked, Gwen_banned)       2      1.091234
420  0.000817          (Azir_banned, Ambessa_picked)       2      1.095015
490  0.000555         (Pantheon_banned, Sion_picked)       2      1.096223
382  0.000557             (Azir_banned, Ahri_picked)       2      1.098776
247  0.000795              (Vi_banned, Leona_picked)       2      1.101350
457  0.000621         (Varus_picked, Taliyah_banned)       2      1.101530
279  0.000559          (Braum_picked, Rumble_banned)       2      1.101578
388  0.000659         (Kalista_banned, Rakan_picked)       2      1.101849
446  0.000529           (Ezreal_banned, Rell_picked)       2      1.101873
345  0.000859            (Taliyah_picked, Vi_banned)       2      1.101943
338  0.001005         (Alistar_picked, Varus_banned)       2      1.103397
349  0.000699      (Taliyah_picked, Pantheon_banned)       2      1.106091
480  0.000597           (Vi_banned, Pantheon_picked)       2      1.106863
334  0.000831        (Alistar_picked, Rumble_banned)       2      1.108535
273  0.000971              (Vi_banned, Varus_picked)       2      1.109599
479  0.000633        (Varus_banned, Pantheon_picked)       2      1.110206
264  0.000523           (Rumble_picked, Yone_banned)       2      1.111550
357  0.000581         (Ambessa_banned, Corki_picked)       2      1.112830
459  0.000691      (Taliyah_banned, Xin Zhao_picked)       2      1.113200
387  0.000647             (Gwen_banned, Ahri_picked)       2      1.113546
443  0.001139        (Varus_banned, Xin Zhao_picked)       2      1.118375
424  0.000643               (Vi_banned, Jhin_picked)       2      1.118389
393  0.000951           (Rakan_picked, Varus_banned)       2      1.118513
394  0.000779            (Azir_banned, Rakan_picked)       2      1.119327
299  0.000507            (Jayce_banned, Azir_picked)       2      1.120159
408  0.000675        (Rumble_picked, Kalista_banned)       2      1.121456
472  0.000561        (Kai'Sa_picked, Kalista_banned)       2      1.122045
243  0.000557         (Corki_picked, Skarner_banned)       2      1.123176
368  0.000975          (Ezreal_picked, Varus_banned)       2      1.124636
488  0.000609             (Azir_banned, Sion_picked)       2      1.126942
296  0.000825            (Azir_picked, Varus_banned)       2      1.127509
267  0.000511          (Taliyah_picked, Yone_banned)       2      1.127687
441  0.000941         (Azir_banned, Xin Zhao_picked)       2      1.128735
445  0.001079         (Gwen_banned, Xin Zhao_picked)       2      1.129335
313  0.001023           (Varus_banned, Corki_picked)       2      1.131718
440  0.000949       (Rumble_banned, Xin Zhao_picked)       2      1.132136
448  0.000585            (Vi_picked, Kalista_banned)       2      1.133321
409  0.000971          (Rumble_picked, Varus_banned)       2      1.134822
301  0.000685           (Azir_picked, Rumble_banned)       2      1.137513
339  0.000795      (Alistar_picked, Pantheon_banned)       2      1.138039
347  0.000775        (Taliyah_picked, Rumble_banned)       2      1.142711
246  0.000525             (Vi_banned, Maokai_picked)       2      1.144153
432  0.000593       (Vi_banned, Miss Fortune_picked)       2      1.144350
468  0.000641        (Neeko_banned, Xin Zhao_picked)       2      1.146529
369  0.000615          (Jayce_banned, Ezreal_picked)       2      1.146618
351  0.000575        (Ambessa_banned, Ezreal_picked)       2      1.148292
311  0.000673         (Varus_banned, Sejuani_picked)       2      1.148930
406  0.000753          (Rumble_picked, Poppy_banned)       2      1.149446
444  0.000901     (Pantheon_banned, Xin Zhao_picked)       2      1.153452
481  0.000617         (Gwen_banned, Pantheon_picked)       2      1.153505
329  0.000519          (Poppy_banned, Aurora_picked)       2      1.155928
245  0.000579       (Ambessa_picked, Skarner_banned)       2      1.157742
431  0.000637    (Varus_banned, Miss Fortune_picked)       2      1.162827
256  0.000523          (Aurora_banned, Varus_picked)       2      1.163359
466  0.000543           (Neeko_banned, Rakan_picked)       2      1.163511
261  0.000593            (Yone_banned, Varus_picked)       2      1.165586
260  0.000527         (Renekton_picked, Gwen_banned)       2      1.168022
274  0.000891          (Rumble_banned, Varus_picked)       2      1.170250
483  0.000551         (Orianna_banned, Corki_picked)       2      1.170552
364  0.000961             (Vi_banned, Ezreal_picked)       2      1.171697
294  0.000605          (Kalista_banned, Azir_picked)       2      1.175403
353  0.000583        (Rumble_picked, Ambessa_banned)       2      1.179620
254  0.000521         (Ambessa_banned, Leona_picked)       2      1.182150
241  0.000741          (Rell_picked, Skarner_banned)       2      1.184870
428  0.000677             (Jhin_picked, Gwen_banned)       2      1.187340
350  0.000923          (Taliyah_picked, Gwen_banned)       2      1.193908
335  0.000833         (Alistar_picked, Poppy_banned)       2      1.194416
426  0.000595             (Azir_banned, Jhin_picked)       2      1.196006
469  0.000541         (Taliyah_picked, Neeko_banned)       2      1.196049
439  0.001153           (Vi_banned, Xin Zhao_picked)       2      1.196649
361  0.000617             (Vi_banned, Viktor_picked)       2      1.198716
272  0.000781         (Kalista_banned, Varus_picked)       2      1.200059
489  0.000653           (Rumble_banned, Sion_picked)       2      1.201666
331  0.000577           (Azir_banned, Aurora_picked)       2      1.201872
258  0.000529          (Aurora_banned, Corki_picked)       2      1.204135
298  0.000835               (Vi_banned, Azir_picked)       2      1.206214
342  0.000593               (Vi_banned, Gwen_picked)       2      1.207879
248  0.000653         (Kalista_banned, Leona_picked)       2      1.216427
259  0.000507         (Rumble_picked, Aurora_banned)       2      1.219232
341  0.000639            (Varus_banned, Gwen_picked)       2      1.231229
430  0.000557   (Rumble_banned, Miss Fortune_picked)       2      1.235438
463  0.000581          (Rumble_picked, Neeko_banned)       2      1.236950
427  0.000577         (Pantheon_banned, Jhin_picked)       2      1.237847
399  0.000715           (Jayce_banned, Varus_picked)       2      1.249139
310  0.000693            (Vi_banned, Sejuani_picked)       2      1.250465
384  0.000545          (Kalista_banned, Ahri_picked)       2      1.250787
286  0.000735        (K'Sante_picked, Rumble_banned)       2      1.253291
474  0.000891          (Kai'Sa_picked, Varus_banned)       2      1.253328
411  0.000655        (Rumble_picked, Taliyah_banned)       2      1.255885
270  0.000577      (Pantheon_banned, Orianna_picked)       2      1.263222
471  0.000689          (Poppy_banned, Kai'Sa_picked)       2      1.265916
344  0.001045         (Taliyah_picked, Varus_banned)       2      1.267985
484  0.000545       (Taliyah_picked, Orianna_banned)       2      1.269955
404  0.001109            (Poppy_banned, Rell_picked)       2      1.270779
374  0.000771           (Azir_banned, Wukong_picked)       2      1.276261
269  0.000623          (Azir_banned, Orianna_picked)       2      1.277863
465  0.000643         (Alistar_picked, Neeko_banned)       2      1.285841
378  0.000583        (Wukong_picked, Taliyah_banned)       2      1.296168
284  0.000525       (K'Sante_picked, Skarner_banned)       2      1.342897
449  0.000541            (Vi_picked, Skarner_banned)       2      1.343557
240  0.000683         (Varus_picked, Skarner_banned)       2      1.345405
379  0.000769       (Wukong_picked, Pantheon_banned)       2      1.358517
359  0.000719              (Vi_banned, Jayce_picked)       2      1.362019
383  0.000659            (Poppy_banned, Ahri_picked)       2      1.389364
486  0.000565           (Xayah_picked, Varus_banned)       2      1.393922
244  0.000665        (Ezreal_picked, Skarner_banned)       2      1.397693
375  0.000795          (Poppy_banned, Wukong_picked)       2      1.406801
414  0.000531        (Rumble_picked, Alistar_banned)       2      1.440430
436  0.000721            (Braum_banned, Rell_picked)       2      1.440820
308  0.000595       (Kalista_banned, Sejuani_picked)       2      1.443624
363  0.000891        (Kalista_banned, Ezreal_picked)       2      1.460498
416  0.001021         (Poppy_banned, Ambessa_picked)       2      1.462565
300  0.000653          (Azir_picked, Taliyah_banned)       2      1.463869
297  0.000591             (Yone_banned, Azir_picked)       2      1.468243
495  0.000609             (Azir_banned, Ryze_picked)       2      1.468956
493  0.000561          (Ambessa_banned, Sion_picked)       2      1.470678
405  0.000507         (Alistar_picked, Rakan_banned)       2      1.489347
482  0.000505        (Rakan_picked, Nautilus_banned)       2      1.504467
390  0.000987           (Poppy_banned, Rakan_picked)       2      1.515712
429  0.000591  (Kalista_banned, Miss Fortune_picked)       2      1.533170
358  0.000605         (Kalista_banned, Jayce_picked)       2      1.541059
452  0.000875              (Vi_picked, Poppy_banned)       2      1.556829
309  0.000503       (Sejuani_picked, Skarner_banned)       2      1.564731
289  0.000645       (Ambessa_banned, K'Sante_picked)       2      1.566686
447  0.000615          (Varus_picked, Ezreal_banned)       2      1.577490
492  0.001121             (Sion_picked, Gwen_banned)       2      1.808935
434  0.000517         (Kai'Sa_banned, Ezreal_picked)       2      1.823767
415  0.000917          (Alistar_banned, Rell_picked)       2      1.866607
438  0.000635           (Leona_picked, Braum_banned)       2      1.894841
497  0.000523      (Trundle_picked, Pantheon_banned)       2      1.901572
437  0.000713        (Nautilus_picked, Braum_banned)       2      1.918414
470  0.000549              (Vi_picked, Xayah_banned)       2      3.601760
372  0.000863      (Renekton_banned, Ambessa_picked)       2      3.669028

In [70]:
frequent_itemsets_pb[frequent_itemsets_pb["itemsets"]==set([i])]["support"]

25    0.030006
Name: support, dtype: float64

In [61]:
norms

[38   NaN
 86   NaN
 Name: support, dtype: float64,
 55   NaN
 67   NaN
 Name: support, dtype: float64,
 30   NaN
 86   NaN
 Name: support, dtype: float64,
 43   NaN
 86   NaN
 Name: support, dtype: float64,
 83   NaN
 89   NaN
 Name: support, dtype: float64,
 25   NaN
 89   NaN
 Name: support, dtype: float64,
 25   NaN
 55   NaN
 Name: support, dtype: float64,
 89    NaN
 144   NaN
 Name: support, dtype: float64,
 5    NaN
 25   NaN
 Name: support, dtype: float64,
 83   NaN
 86   NaN
 Name: support, dtype: float64,
 5    NaN
 83   NaN
 Name: support, dtype: float64,
 25   NaN
 86   NaN
 Name: support, dtype: float64]

In [26]:
0.03797 * 0.030006

0.0011393278199999999

In [30]:
0.001175/0.0011393278199999999

1.031309847239577

In [27]:
print(frequent_itemsets_pb[frequent_itemsets_pb["itemsets"]==set(["Poppy_banned"])]["support"])
frequent_itemsets_pb[frequent_itemsets_pb["itemsets"]==set(["Ambessa_picked"])]["support"]

55    0.029079
Name: support, dtype: float64

67    0.024005
Name: support, dtype: float64

In [29]:
0.001021/(0.029079*0.024005)

1.4626639728149646

Varus is not really a good counter for rumble according to https://u.gg/lol/champions/rumble/counter, though we are seeing Varus appear high so he may just be a high priority ban

In [113]:
te = TransactionEncoder()
te_ary = te.fit(ban_set).transform(ban_set)
df_ap_ban = pd.DataFrame(te_ary, columns=te.columns_)

In [116]:
frequent_itemsets_fpg = fpgrowth(df_ap_ban, min_support=0.1,use_colnames=True)
frequent_itemsets_fpg['length'] = frequent_itemsets_fpg['itemsets'].apply(lambda x: len(x))
#freq_greater_1_fpg = frequent_itemsets_fpg[(frequent_itemsets_fpg['length'])>1]
frequent_itemsets_fpg.sort_values(by=["support"])

     support    itemsets  length
1   0.103800   (Skarner)       1
12  0.103850     (Neeko)       1
2   0.104049      (Yone)       1
4   0.109271   (Ambessa)       1
10  0.115289   (Taliyah)       1
7   0.117030     (Jayce)       1
3   0.133045   (Kalista)       1
6   0.144783     (Poppy)       1
13  0.145031  (Pantheon)       1
11  0.154780      (Azir)       1
5   0.155625    (Rumble)       1
9   0.177360      (Gwen)       1
0   0.178852        (Vi)       1
8   0.189048     (Varus)       1

As expected based on above, Varus is just a high priority ban

Can look more into counter picks (IE make each entry the laners for a given game on opposing sides), seperate by whether the team won or not, add a league or patch to see if a champ is really popular in a certain patch or league (could also seperate those into their own subdatasets). Look at the class roles (Tank, Mage etc), llok more clearly at pick ban, IE make the variables "Varus_picked" and "Varus_banned". Normalize by popularity see above